[template]
src = "zabbix_server.conf.tmpl"
dest = "/etc/zabbix/zabbix_server.conf"
keys = [
    "/zabbix/server/db/address",
    "/zabbix/server/db/port",
    "/zabbix/server/db/name",
    "/zabbix/server/db/user",
    "/zabbix/server/db/passwd",
]
